[package]
name = "sqlite-vfs"
version = "0.1.0"
authors = ["Markus Ast <m@rkusa.st>"]
edition = "2021"

[dependencies]
rusqlite = { version = "0.26", features = ["bundled", "wasm32-wasi-vfs"] }
rand = "0.8"
time = { version = "0.3" }
