[package]
name = "sqlite-vfs"
version = "0.1.0"
authors = ["Markus Ast <m@rkusa.st>"]
edition = "2021"

[dependencies]
log = "0.4"
rand = "0.8"
rusqlite = { version = "0.26", features = ["bundled"] }
time = { version = "0.3" }

[patch.crates-io]
rusqlite = { git = "https://github.com/rkusa/rusqlite.git", branch = "wasi" }